### ISSUE TITLE
Inject parameters into test function

### ISSUE THREAD

**Issue by willianhf** [japa/core#33]
## Description

Is there a way to inject parameters into the test function? Something like this:

```js
test('Test description', (assert, context) => {
  ...
})
```

## Package version
3.1.1

**Comment by thetutlage** [comment]
Not now. But this is something I myself want to introduce. If you have bandwidth to work on the feature, then I am all up for accepting the PR. Thanks :)

**Comment by willianhf** [comment]
Do you have some specific API in mind, I was thinking to do into the `hooks`. Something like that:
```ts
function addContext(runner) {
  runner.context = {}
}

configure({ before: [addContext] })
```

**Comment by thetutlage** [comment]
Yup. Already started working on it. The context will be extended using Macros, something we use with AdonisJS. https://docs.adonisjs.com/guides/context#macros

**Comment by diegogit03** [comment]
Please!! this is necessary for i make a mock library!
