### ISSUE TITLE
💡 - Optional sorted / sequential test files

### ISSUE THREAD

**Issue by luizxsoto** [japa/core#41]
## Description

Some test files need other test files to be run first, so making the sort optional would be interesting.

## Package version
```json
"devDependencies": {
  "japa": "^3.1.1",
}
```

## Relevant Information

I was thinking about a Pull Request for this feature, adjusting the "configure" function and the "Loader/loadFiles", so making `filesPaths.sort()` optional and default true.

**Comment by thetutlage** [comment]
Tests relying on other test files/or even other tests is not a great thing to have.

**Comment by luizxsoto** [comment]
> Tests relying on other test files/or even other tests is not a great thing to have.

So maybe in order to better organize the execution sequence, based on the importance of files or another internal rule of the company that uses this lib. A Pull Request to make sort optional, wouldn't that be nice?

**Comment by thetutlage** [comment]
I am trying to understand the use case. I am not sure what you mean by "better organize the execution sequence"? Also, the importance of files can be different for different people in different context

**Comment by luizxsoto** [comment]
Exactly, taking into account that the ordering is by file name, it does not allow different people to order the test files sequence in the way they prefer. Making the ordering optional and setting it to `false`, will make it follow the order passed in the files array.

*Example:*
```js
import { configure } from 'japa'

configure({
  files: ['file 2 that run first', 'file 1 that run second'],
})
```

**Comment by thetutlage** [comment]
The newer version allows defining a custom function for the files property. You can achieve what you need as follows.

```ts
import fastGlob from 'fast-glob'

files: async () => {
  const files = await fastGlob('tests/**/*.spec.js') 
  return files.sort(yourImplementation)
}
```
