### ISSUE TITLE
Can group initialization be asynchronous?

### ISSUE THREAD

**Issue by cawa-93** [japa/core#44]
In my test case, I want to create multiple instances of a model in a database. And run a separate test for each:

```js
test.group('Status code must mee 2xx or 3xx', async (group) => {
  let links = await ShortLinkFactory.createMany(50)

  links.forEach(link => {
    test(link.id, async (assert) => {
      await supertest(link.url)
        .get('/')
        .expect((res) => {
          assert.isAbove(res.statusCode, 200)
          assert.isBelow(res.statusCode, 400)
        })
    })
  })
})
```

Of course I can do everything in one test, but then I do not get a beautiful and convenient log that conveniently displays which links returned the expected result and which failed

**Comment by RomainLanz** [comment]
Hey @cawa-93! 👋🏻 

You may want to use [group hooks](https://github.com/thetutlage/japa#test-groups) to handle that.

**Comment by cawa-93** [comment]
Could you set an example? I thought about it, but couldn't find a way.

```js

test.group('Status code must mee 2xx or 3xx', (group) => {
  let links

  group.before(async () => {
    links = await ShortLinkFactory.createMany(50)
  })

  // Variable 'links' is used before being assigned
  links.forEach(link => {
    test( ... )
  })
})
```

**Comment by thetutlage** [comment]
The groups cannot be asynchronous right now. Once, we all move to ESM + top level await, then this is will possible automatically without changing anything in Japa.

However, what you are trying to do is a better fit for datasets. Datasets are coming in the next version. Following is an example code for the same.

```ts
test('some title', ({ assert }, link) => {
  
})
.with(() => ShortLinkFactory.createMany(50))
```

The above test will run for 50 times.

**Comment by thetutlage** [comment]
The newer version has datasets for this exact use case. Here are the docs https://japa.dev/datasets

Closing it for now.
