### ISSUE TITLE
Custom order for running tests

### ISSUE THREAD

**Issue by un-versed** [japa/core#46]
## Description

There is a pattern to use a custom order for tests?

Actually, I'm using this syntax:

```
1_a_test.spec.ts
2_b_test.spec.ts
3_c_test.spec.ts
4_d_test.spec.ts
```

In VSCode, my files are showed up in the right order, but when Japa tries to run my tests, they're not in the right order.

What's the order Japa try to run tests? I didn't found this clearly in the docs.

**Comment by thetutlage** [comment]
Yup, will be fixed in the next version

**Comment by un-versed** [comment]
@thetutlage Actually I created a fork for it, should I make a PR?

https://github.com/un-versed/japa

I'm exposing a `sort` function, that can be used at configure method in `japaFile.ts`

The code:

```javascript
const collator = new Intl.Collator(undefined, { numeric: true, sensitivity: 'base' })

/**
 * Configure test runner
 */
configure({
  files: ['test/**/*.spec.ts'],
  before: [
    runMigrations,
    runSeeds,
    startHttpServer,
  ],
  after: [rollbackMigrations],
  sort: collator.compare
})
```

I'm using a collator, but you can use any sorting function tho

**Comment by thetutlage** [comment]
Great :) Actually, I am changing the japa a lot. Diving it into a separate runner and separate core. So PR for the old codebase won't help

**Comment by un-versed** [comment]
Oh, I got it 👍🏻 anxious for the new version ☺️

But, there's a chance do add this in the old codebase? Actually I'm using my own package distribution from Japa in npm, just to have this feature in my project.

If there's no chance, I won't write tests for it right now...

**Comment by thetutlage** [comment]
Sure. Feel free to send a PR for the `develop` branch

**Comment by thetutlage** [comment]
The newer version allows defining a custom function for the `files` property. You can achieve what you need as follows.

```ts
import fastGlob from 'fast-glob'

const collator = new Intl.Collator(undefined, { numeric: true, sensitivity: 'base' })

files: async () => {
  const files = await fastGlob('tests/**/*.spec.js') 
  return files.sort(collator)
}
```

Lemme know if you face any issues. We can reopen the issue
