### ISSUE TITLE
Asynchronous datasets / datasets not supported anymore? Multiple chained asynchronous test dependencies

### ISSUE THREAD

**Issue by Arteneko** [japa/core#55]
While having an asynchronous group callback would make this streamlined and very simple, I fail to see how to have multiple asynchronous test dependencies.

Additionally, counting on typescript, the example for typescript intellisense in the documentation seems broken as the typings don't allow this.

## Description

I have two datasets, one being asynchronously mocked, and another being asynchronously built partly based on the first dataset.

On a "simple" approach where test groups would be asynchronous, I would simply need to have line 1 with my first await, and line two with my second await.

The documentation tells me to use the `.with()` property *after a `test()` call*, which per typescript's compiler, doesn't exist.

```
Property 'with' does not exist on type 'RunnerTest'.ts(2339)
```

The *typescript-intellisense-specific documentation* tells me to use the `.with()` property on a `test()` that would've only been called with a single parameter (the test name).
Trying to do so raises multiple errors.

```
Expected 2 arguments, but got 1.ts(2554)
[index.d.ts(29, 45): ]()An argument for 'callback' was not provided.
Property 'with' does not exist on type 'RunnerTest'.ts(2339)
```

Is this feature still supported ?

If not, how would I expect to have asynchronous dataset initialization that wouldn't require repeated boilerplate code?

## Package version

- ^4.0.0

**Comment by thetutlage** [comment]
Please share the code you have a written

**Comment by Arteneko** [comment]
```ts
test.group('computeMovementSummary()', async () => {
  const counterparties = await Promise.all([
    'input',
    'pool',
    'output',
  ].map((type: CounterpartyType) => CounterpartiesFactory.merge({ type }).create()))
  const [input$$, pool$$, output$$] = counterparties;

  const movements: { origin: string; destination: string; amount: number; }[] = [
    { origin: pool$$.id, destination: output$$.id, amount: 1000 },
    { origin: input$$.id, destination: pool$$.id, amount: 1000 },
  ]

  test.group('with only one movement', () => {
    const summary = computeMovementSummary([movements[0]], counterparties)

    test('it should return the destination as pivot', (assert) => {
      assert.equal(summary.pivot.id, pool$$.id)
    })

    test('it should return the base amount', (assert) => {
      assert.equal(summary.amount, movements[0].amount)
    })
  })

  test.group('with multiple movements (case: a reimbursement)', () => {
    const summary = computeMovementSummary(movements, counterparties)

    test('it should return the first destination as pivot', (assert) => {
      assert.equal(summary.pivot.id, pool$$.id)
    })

    test('it should return a nil amount', (assert) => {
      assert.equal(summary.amount, 0)
    })
  })
})
```

This is the code "in natural implementation way", for the two examples, here's what I tried.

```ts
// Property 'with' does not exist on type 'RunnerTest'.ts(2339)
test('it should return the first destination as pivot', (assert, c) => {
  assert.equal(summary.pivot.id, c[1].id)
}).with(async () => await Promise.all([
    'input',
    'pool',
    'output',
  ].map((type: CounterpartyType) => CounterpartiesFactory.merge({ type }).create())))
```

```ts
// Expected 2 arguments, but got 1.ts(2554)
test('it should return the first destination as pivot')
.with(async () => await Promise.all([
    'input',
    'pool',
    'output',
  ].map((type: CounterpartyType) => CounterpartiesFactory.merge({ type }).create())))
```

**Comment by thetutlage** [comment]
What version of `@japa/runner` are you using?

**Comment by Arteneko** [comment]
I didn't have `@japa/runner` installed (since it wasn't mentioned in [adonis' testing recipe](https://docs.adonisjs.com/cookbooks/testing-adonisjs-apps)), but after installing it, it's using the latest, so `@japa/runner@2.0.3`

**Comment by thetutlage** [comment]
Then please follow the upgrade docs first. https://japa.dev/releases/version-5

**Comment by Arteneko** [comment]
That... could be useful to mention it on Adonis, at least as a content warning for an obsolete guide...

**Comment by thetutlage** [comment]
Agree. The cookbooks needs an updated. I will look into it :). Closing this issue for now
