### ISSUE TITLE
[Feature suggestions] Mock Functions

### ISSUE THREAD

**Issue by assaad97** [japa/core#71]
### Package version

@japa/runner v2.5.1

### Describe the bug

Note : this is not a bug, this is a feature suggestion (unless it already exists, then its my bad 😅, please refer the doc fo it if possible)

Hi,

The feature im suggesting is the possiblity to mock functions, let suppose i have a class User:
`Class User {
    ...methods and properties

    public someMethode(userId: number) {
        // some logic
    }

    public getUserInfo(userId: number) {
        if (condition) {
            this.someMethode(userId)
        }

        // rest of function logic
    }
}`

i define a test for User::getUserInfo:

`
test.group("User.getUserInfo", () => {
    const instance = new User();

    test("success", async ({ assert }, userId) => {
        const userInfo = instance.getUserInfo(userId)

        // the different assertions
    }).with([
        1,
        15975,
        579846
    ])
});
`

is there a way to mock User::someMethode that is going to be called inside the method getUserInfo, throught the test, so i can have an information that it was actually called.

thank you in advance for the response, and please correct me if this already exists and/or if its not technically possible.

**Comment by thetutlage** [comment]
How about using SinonJS for this? https://sinonjs.org/releases/v15/mocks/

**Comment by assaad97** [comment]
Hello @thetutlage,

Thank you for the response, I have never heard of sinonjs, I experimented with it alongside adonisjs test suites, its a great tool (sinonjs), it offers everything I need and more, its utilisation alongside adonisjs tests is super simple.

Thank you for providing such a great tool, and for the response again.

Regards.
Assaad.
